<?php

/**
* Auto assigning garage to a car on car creation event.
*/

function get_user_node_by_type($node_type, $uid){
  $nodes = array();
  $nids = db_query('SELECT nid FROM {node} WHERE uid = :uid AND type = :type', array(':uid' => $uid, ':type' => $node_type))->fetchCol();
  return $nids;
}


function iMODIFY_custom_node_presave($node) {
  if ($node->type =='cars') {
      $nids = get_user_node_by_type('garage', $node->uid);
    $node->field_car_garage['und']['0']['nid']= $nids[0];
    
  }
}
/**
*Custom redirect after login (role based) 
*
*/
function iMODIFY_custom_user_login(&$edit, $account) {
if($_GET['destination'] == ''){    
  if(in_array('siteadmin', $account->roles)){
      $url = 'http://'.$_SERVER['HTTP_HOST'].'/admin/index';
	header('Location: ' . $url);
	exit();
    }elseif (in_array('Automotive Supplier', $account->roles)) {
      $result = db_query('SELECT n.nid FROM {node} n WHERE n.type= :type AND n.uid = :uid order by n.nid DESC limit 0,1 ', array(':uid' => $account->uid,':type' => 'supplier_profile'));
      $record = $result->fetchCol(); 
	  if(count($record)>0){
	      $profile_id = $record[0];
	      
	}else{ 
	//create default profiles
	$garage_id =  create_node_by_user('garage', $account);
	$profile_id = create_node_by_user('supplier_profile', $account);
	}
	      $url = 'http://'.$_SERVER['HTTP_HOST'].'/supplier-profile/'.$profile_id; 
	      header('Location: ' . $url);
	      exit();
      
    }else{

      $result = db_query('SELECT n.nid FROM {node} n WHERE n.type= :type AND n.uid = :uid order by n.nid DESC limit 0,1 ', array(':uid' => $account->uid,':type' => 'cars')); 
      $record = $result->fetchCol(); 
	  if(count($record)>0){
	    $car_nid = $record[0];
	}else{
	//create default profiles
	$garage_id =  create_node_by_user('garage', $account);
	$car_nid = create_node_by_user('cars', $account);
       }
	    $url = 'http://'.$_SERVER['HTTP_HOST'].'/car-profile/'.$car_nid; 
	    header('Location: ' . $url);
	    exit();
}
}  
}

/**
*creating car status on adding new car
*/

function iMODIFY_custom_node_insert($node) {
    if ($node->type =='cars') {
	  create_node_car_status($node);
      }
}

/**
* function for saving a node 
*/

function create_node_car_status($refered_node){ 
    $node = new stdClass();
    $node->type = 'car_status';
    node_object_prepare($node);
  
    $node->title    = $refered_node->title.' Status';
    $node->language = LANGUAGE_NONE;
    $node->field_car['und']['0']['nid']= $refered_node->nid;
    $node->uid= $refered_node->uid;

    node_save($node);
}

function create_node_by_user($type, $account){ 
    $node = new stdClass();
      $node->type = $type;
      node_object_prepare($node);
  if($type == 'cars'){
      $node->title    = $account->name.' - Car 1';
   }elseif($type == 'garage'){
     $node->title    = $account->name.' Garage';
   }else{
     $node->title    = $account->name;
   }
      $node->language = LANGUAGE_NONE;
      $node->uid= $account->uid;

     node_save($node);
return $node->nid;
}
